### PR TITLE
Add OpenLava support as backend job scheduler

### PR DESCRIPTION
**Pull request by fengliteraproc**
Hi Team,
We've tested BatchJobs on OpenLava job workload schedule system and would like to add this support to the package.

We've added below files:
file R/clusterFunctionsOpenLava.R for job operations.
file examples/cfOpenLava/openlava.tmpl as template
file examples/cfOpenLava/simple.tmpl as template
file external_tests/openlava.R as test example
file man/makeClusterFunctionsOpenLava.Rd as man page

We've modified below existing man pages to add OpenLava man page referrals.
 man/makeClusterFunctions.Rd
 man/makeClusterFunctionsInteractive.Rd
 modified:   man/makeClusterFunctionsLSF.Rd
 modified:   man/makeClusterFunctionsLocal.Rd
 modified:   man/makeClusterFunctionsMulticore.Rd
 modified:   man/makeClusterFunctionsSGE.Rd
 modified:   man/makeClusterFunctionsSLURM.Rd
 modified:   man/makeClusterFunctionsSSH.Rd
 modified:   man/makeClusterFunctionsTorque.Rd

Thanks,

Feng Li
Teraproc Inc.
3601 Highway 7 East, #400
Markham, Ontario L3R 0M3 Canada
Phone: (905) 479 6671 ext. 4451
Mobile: (647) 967 1891
Email: fli@teraproc.com

### CODE REVIEW

**Comment by fengliteraproc** [comment]
Hi, team. thanks for handling this. I see one failure for man pages files. Is there anything we can do to get this fixed? 

thanks,
Feng

**Comment by berndbischl** [comment]
Thanks. Will review now for 5 min

**Comment by fengliteraproc** [comment]
Thanks!

**Comment by berndbischl** [comment]
Looks ok to me

1) Can you add your name as contributor to NEWS please or tell me here?

2) I dont see man problems in the check? 

3) Please make sure that the current version runs really on your cluster.

**Comment by fengliteraproc** [comment]
Thank you. Teraproc Inc. that I’m from can be the name of the contributor. Teraproc is providing OpenLava technical support and also for this OpenLava feature in BatchJobs package.
The code has been tested on our cluster with OL 3.0.1.

Would you please also update DESCRIPTION and README.md file to reflect OpenLava support?

Thanks,
Feng

**Pull request merged**
